### ISSUE TITLE
Add support for CURLOPT_SSL_VERIFYPEER ?

### ISSUE THREAD

**Issue by sviscapi** [irods/irods_microservice_plugins_curl#20]
Dear iRODS team,

Would it be possible for you to add support for CURLOPT_SSL_VERIFYPEER in irods_ms_plugin_curl.cpp ? 

I'm trying to use the iRODS curl plugin to POST some stuff to an HTTPS API using self-signed certificates, and it obviously doesn't work.

Best regards,

Samuel, from CINES (Montpellier, France)

https://www.cines.fr/en/

**Comment by trel** [comment]
Is this still necessary - or did you find a workaround?

**Comment by sviscapi** [comment]
Hi Terrell,

This is no longer necessary, Daniel showed me how to do something very similar using Python.

Cheers, Samuel
