### ISSUE TITLE
libcurl3 dependency is problematic, should be libcurl3-gnutls

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_microservice_plugins_curl#26]
- [x] master
- [x] 4-2-stable
----
The debian package depends on `libcurl3`:
https://github.com/irods/irods_microservice_plugins_curl/blob/9e3a6f9cd9658dbdd21dff4949215631061ee1d3/CMakeLists.txt#L159

We build against `libcurl4-gnutls-dev` on xenial and bionic:
https://github.com/irods/irods_development_environment/blob/f33141d780d5f5e73fd971e2238362fd08490cc3/Dockerfile.irods_core_builder.ubuntu16#L57
https://github.com/irods/irods_development_environment/blob/f33141d780d5f5e73fd971e2238362fd08490cc3/Dockerfile.irods_core_builder.ubuntu18#L58

On xenial, `libcurl3` and `libcurl4-gnutls-dev` come from the [same source package](https://packages.ubuntu.com/source/xenial/curl)
That source package [also exists](https://packages.ubuntu.com/source/bionic/curl) for bionic, but `libcurl3` became `libcurl4`. On bionic, `libcurl3` comes from a [different source package](https://packages.ubuntu.com/source/bionic/curl3) and is incompatible with `libcurl4`. Installing `libcurl3` breaks everything that depends on `libcurl4`, including the `curl` command itself.

Furthermore, the only curl library that `libmsiCurlGetObj.so`, `libmsiCurlGetStr.so`, and `libmsiCurlPost.so` link to is `libcurl-gnutls.so.4`, which is not in the `libcurl3` ([xenial](https://packages.ubuntu.com/xenial/amd64/libcurl3/filelist) nor [bionic](https://packages.ubuntu.com/bionic/amd64/libcurl3/filelist)) or [`libcurl4`](https://packages.ubuntu.com/bionic/amd64/libcurl3/filelist) packages.
Instead, it's in `libcurl3-gnutls` in both [xenial](https://packages.ubuntu.com/xenial/amd64/libcurl3-gnutls/filelist) and [bionic](https://packages.ubuntu.com/bionic/amd64/libcurl3-gnutls/filelist)

**Comment by trel** [comment]
that makes my head hurt.    thanks for untangling.
