### ISSUE TITLE
Install of 'unittest-xml-reporting==1.14.0' in test hook breaks tests

### ISSUE THREAD

**Issue by FifthPotato** [irods/irods_microservice_plugins_curl#70]
- [x] main
- [x] 4-3-stable

---

Testing breaks on ubuntu24 due to the install of unittest-xml-reporting==1.14.0 in the test hook.
The fix is to delete 
https://github.com/irods/irods_microservice_plugins_curl/blob/ea4e8df9143e7f26f3498cc8aac83368348821a5/irods_consortium_continuous_integration_test_hook.py#L12

**Comment by trel** [comment]
why does it break?

**Comment by trel** [comment]
ah, so old it's causing conflicts...    got it.

same as https://github.com/irods/irods_capability_storage_tiering/issues/275

**Comment by korydraughn** [comment]
@FifthPotato Please check the boxes and close if completed.
